#!/usr/bin/env perl
#
# context-inheritance - Entry point for context inheritance (trampolines to version-specific script)
#
# Usage: context-inheritance <task-path> [--format=json]
#

use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../../../lib";
use CWF::Common qw(check_perl5opt);
use CWF::VersionRouter qw(detect_version route_to_version);

check_perl5opt();
my $version = detect_version($ARGV[0] || '');
route_to_version("context-inheritance", $version, @ARGV);
