#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../../../lib";
use CWF::Common qw(check_perl5opt);
use Cwd qw(getcwd abs_path);

check_perl5opt();

# Get git root
my $git_root = `git rev-parse --show-toplevel 2>&1`;
chomp $git_root;

# Get current working directory
my $cwd = getcwd();

# Output
print "Git repo root: \"$git_root\"\n";
print "Current directory: \"$cwd\"\n";

exit 0;
