#!/usr/bin/env perl
#
# status-aggregator - Entry point for status aggregation (trampolines to version-specific script)
#
# Usage: status-aggregator [task-path] [--workflow] [--no-workflow] [--limit=N] [--sort=modified] [--format=json]
#

use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../../../lib";
use CWF::Common qw(check_perl5opt);
use CWF::VersionRouter qw(detect_version route_to_version);

check_perl5opt();
my $version = detect_version($ARGV[0] || '');
route_to_version("status-aggregator", $version, @ARGV);
