// Code generated by go generate; DO NOT EDIT.

package main

// getVersionString returns the version string
func getVersionString() string {
	return "v0.0.13-UNCOMMITTED-27d809de"
}

// getGitCommit returns the git commit hash
func getGitCommit() string {
	return "27d809de89a35180b63d72cca134817bd9252aa6"
}
