// Code generated by go generate; DO NOT EDIT.

package main

// getVersionString returns the version string
func getVersionString() string {
	return "v0.0.13-UNCOMMITTED-c1b5e23a"
}

// getGitCommit returns the git commit hash
func getGitCommit() string {
	return "c1b5e23a8bd78978f301aa425ddc4e5f3e78d44b"
}
