// Code generated by go generate; DO NOT EDIT.

package main

// getVersionString returns the version string
func getVersionString() string {
	return "v0.0.13-UNCOMMITTED-94c1d5bb"
}

// getGitCommit returns the git commit hash
func getGitCommit() string {
	return "94c1d5bb6517960fb14d7bc1391bafe7907d9578"
}
