package main

import (
	"encoding/json"
	"fmt"
	"os"
	"runtime"
)

// handleVersion handles --version flag (alias for handleVersionCommand with no args)
func handleVersion() {
	handleVersionCommand([]string{})
}

// handleVersionCommand handles the "dcfh version" command
func handleVersionCommand(args []string) {
	if len(args) != 0 {
		outputError("Usage: dcfh version")
		os.Exit(1)
	}

	format := validateOutputFormat()

	if format == OutputJSON {
		versionJSON := map[string]any{
			"version": getVersionString(),
		}

		// Include detailed info if verbose
		if options.GetInt("verbose") > 0 {
			versionJSON["git_commit"] = getGitCommit()
			versionJSON["go_version"] = runtime.Version()
			versionJSON["supported_index_formats"] = []string{"v0"}
			versionJSON["description"] = "Directory Cache File Hash - A fast file indexing and duplicate detection tool"
		}

		jsonBytes, _ := json.MarshalIndent(versionJSON, "", "  ")
		fmt.Println(string(jsonBytes))
	} else {
		// Simple output by default: just the version
		fmt.Println(getVersionString())

		// Detailed output if verbose
		if options.GetInt("verbose") > 0 {
			fmt.Printf("Git commit: %s\n", getGitCommit())
			fmt.Printf("Go version: %s\n", runtime.Version())
			fmt.Printf("Supported index formats: v0\n")
			fmt.Printf("Description: Directory Cache File Hash - A fast file indexing and duplicate detection tool\n")
		}
	}
}

// getVersionString and getGitCommit are generated by go generate
