package main

import (
	"fmt"
	"runtime"

	"github.com/spf13/cobra"
)

var versionCmd = &cobra.Command{
	Use:   "version",
	Short: "Show version information",
	Args:  cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		format := getOutputFormat()

		if format == OutputJSON {
			versionJSON := map[string]any{
				"version": getVersionString(),
			}

			if flagVerbose > 0 {
				versionJSON["git_commit"] = getGitCommit()
				versionJSON["go_version"] = runtime.Version()
				versionJSON["supported_index_formats"] = []string{"v0"}
				versionJSON["description"] = "Directory Cache File Hash - A fast file indexing and duplicate detection tool"
			}

			outputJSON(versionJSON)
		} else {
			fmt.Println(getVersionString())

			if flagVerbose > 0 {
				fmt.Printf("Git commit: %s\n", getGitCommit())
				fmt.Printf("Go version: %s\n", runtime.Version())
				fmt.Printf("Supported index formats: v0\n")
				fmt.Printf("Description: Directory Cache File Hash - A fast file indexing and duplicate detection tool\n")
			}
		}

		return nil
	},
}

func init() {
	rootCmd.AddCommand(versionCmd)
}

// getVersionString and getGitCommit are generated by go generate
