// Code generated by go generate; DO NOT EDIT.

package main

// getVersionString returns the version string
func getVersionString() string {
	return "v0.0.10-UNCOMMITTED-4788f330"
}

// getGitCommit returns the git commit hash
func getGitCommit() string {
	return "4788f3309754a73ab6867c9e645506b6895bec5d"
}
