//go:build ignore

package main

import (
	"fmt"
	"os"
	"os/exec"
	"strings"
)

func main() {
	version, commit, err := getVersionInfo()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error getting version info: %v\n", err)
		os.Exit(1)
	}

	// Generate version.go file
	content := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.

package main

// getVersionString returns the version string
func getVersionString() string {
	return "%s"
}

// getGitCommit returns the git commit hash
func getGitCommit() string {
	return "%s"
}
`, version, commit)

	err = os.WriteFile("version.go", []byte(content), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing version.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated version.go: %s (commit %s)\n", version, commit)
}

func getVersionInfo() (version, commit string, err error) {
	// Get current commit hash
	commitCmd := exec.Command("git", "rev-parse", "HEAD")
	commitOutput, err := commitCmd.Output()
	if err != nil {
		return "v0.0.0", "unknown", nil // Fallback if not in git repo
	}
	commit = strings.TrimSpace(string(commitOutput))
	shortCommit := commit
	if len(commit) > 8 {
		shortCommit = commit[:8]
	}

	// Get the latest tag
	tagCmd := exec.Command("git", "describe", "--tags", "--exact-match", "HEAD")
	tagOutput, err := tagCmd.Output()
	if err == nil {
		// We're exactly on a tag
		version = strings.TrimSpace(string(tagOutput))
		return version, commit, nil
	}

	// Not on a tag, get the latest tag and add commit info
	latestTagCmd := exec.Command("git", "describe", "--tags", "--abbrev=0")
	latestTagOutput, err := latestTagCmd.Output()
	if err != nil {
		// No tags found
		version = fmt.Sprintf("v0.0.0-%s", shortCommit)
		return version, commit, nil
	}

	latestTag := strings.TrimSpace(string(latestTagOutput))
	version = fmt.Sprintf("%s-%s", latestTag, shortCommit)
	return version, commit, nil
}