#!/usr/bin/env perl
use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../../lib";
use CWF::TaskState qw(status_set);

my $PROG = 'cwf-set-status';

unless (@ARGV == 2) {
    warn "Usage: $PROG <file-path> <new-status>\n";
    exit 1;
}

eval { status_set(@ARGV) };
if ($@) {
    warn "$PROG: error: $@";
    exit 1;
}
