#!/usr/bin/env perl
#
# create - Create task workflow files (ALWAYS v2.1 format)
#
# Usage: create --task-type=TYPE --destination=PATH --task-num=NUM --description=DESC [--format=json]
#

use strict;
use warnings;
use utf8;
use FindBin;
use lib "$FindBin::Bin/../../../lib";
use CWF::Common qw(check_perl5opt);

check_perl5opt();

# Note: ALWAYS use v2.1 - no version detection
# This ensures new tasks are created with latest workflow file format
my $parent_dir = "$FindBin::Bin/..";
exec("$parent_dir/template-copier-v2.1", @ARGV) or die "Failed to exec template-copier-v2.1: $!\n";
